sonar.projectKey=2401416-q4-web-application
sonar.projectName=2401416 Q4 Web Application
sonar.projectVersion=1.0
sonar.sources=app/src,app/public
sonar.tests=app/test
sonar.test.inclusions=app/test/**
sonar.exclusions=app/node_modules/**,app/ui-failure.png
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
